include:
 - path: ./caddy-compose.yaml
 - path: ./liteLLM-compose.yaml
 - path: ./metrics-compose.yaml
 - path: ./openwebui-compose.yaml
 - path: ./redis-compose.yaml

networks:
  monitoring:
    driver: bridge
  internal:
    driver: bridge
  web:
    driver: bridge

